In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
#Python2を使っている場合は、5/2が2にならないように、以下の1行を実行
from __future__ import division

In [4]:
#アレイを作る
arr1 = np.array([1,2,3,4],[8,9,10,11])
arr1

TypeError: data type not understood

In [5]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [6]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [7]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
#1をアレイの各要素で割ってみる
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [10]:
#累乗を計算
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)